### ISSUE TITLE
Notes on other cities

### ISSUE THREAD

**Issue by cara-lgrow** [citizenlabsgr/adopt-a-drain#6]
LGROW's likes and dislikes of other cities who have used the same code for similar programs
[Notes on other programs.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a737f09cafb1c0011849739/125516c66e82c728ace21e0d46c69b8e2691c3a681a9b057ac58e2d4395428743b05ae3832c9a138ad4d71040c1b5ca6535d0e40a9fc8023f5e43424820e58edd16c0b71c23542fdba9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3f1604118df65b31a59e4dda15.docx)

**Comment by Wilfongjt** [comment]
Break down:

~San Francisco
We like the way the icons show up differently on all of the location markers for the drains and are different colors (hearts if adopted, other symbol if the drain is available for adoption). We also like the “find drains” option on this one.~
This is already done

**Comment by Wilfongjt** [comment]
~Riverside, CA
http://www.adoptadrainriverside.com/
Since we will have so many partners, our sidebar (left side) will probably look more like this:~

~Our partners might have to be listed on a separate page since we will have so many. We would at least like LGROW and Citizens lab mentioned on the main map page. This is probably something we will have to discuss with the communities.  We do like the option that San Francisco (below) has to include a short training/informational video in the sidebar.
Riverside (above) also has a different log-in option than other sites (click on the ‘I have signed up’ or ‘I haven’t signed up’ option). We do not think it is necessary for residents to have to enter a phone number- email is sufficient.~ 

~Riverside looks the same as Boston’s Adopt-a-Hydrant program: http://www.adoptahydrant.org/~

This is done

**Comment by Wilfongjt** [comment]
St. Paul, MN
https://www.adopt-a-drain.org/
The pop-up before you enter the site is nice because it offers instruction and education click-throughs

Moved to "Splash Screen #59"

**Comment by Wilfongjt** [comment]
Broken up or done
